import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/vendor/@quantum_web-3.0.0/package/dist/css/quantum.min.css" />
        <link rel="stylesheet" href="/vendor/@quantum_symbols-1.0.0/package/font/quantum-symbols.css" />
      </head>
      <body>

        {children}
       
        <Script 
          src="/vendor/bootstrap-5.3.3/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/vendor/@quantum_web-3.0.0/package/dist/js/quantum.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
